/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as StaminaCalculatorRouteImport } from './routes/stamina-calculator';
import { Route as RunnersRouteImport } from './routes/runners';
import { Route as SimulationRouteImport } from './routes/_simulation';
import { Route as RunnersIndexRouteImport } from './routes/runners/index';
import { Route as SimulationIndexRouteImport } from './routes/_simulation/index';
import { Route as RunnersNewRouteImport } from './routes/runners/new';
import { Route as SimulationUmaBassinRouteImport } from './routes/_simulation/uma-bassin';
import { Route as SimulationSkillBassinRouteImport } from './routes/_simulation/skill-bassin';
import { Route as RunnersRunnerIdEditRouteImport } from './routes/runners/$runnerId.edit';

const StaminaCalculatorRoute = StaminaCalculatorRouteImport.update({
  id: '/stamina-calculator',
  path: '/stamina-calculator',
  getParentRoute: () => rootRouteImport,
} as any);
const RunnersRoute = RunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => rootRouteImport,
} as any);
const SimulationRoute = SimulationRouteImport.update({
  id: '/_simulation',
  getParentRoute: () => rootRouteImport,
} as any);
const RunnersIndexRoute = RunnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunnersRoute,
} as any);
const SimulationIndexRoute = SimulationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SimulationRoute,
} as any);
const RunnersNewRoute = RunnersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RunnersRoute,
} as any);
const SimulationUmaBassinRoute = SimulationUmaBassinRouteImport.update({
  id: '/uma-bassin',
  path: '/uma-bassin',
  getParentRoute: () => SimulationRoute,
} as any);
const SimulationSkillBassinRoute = SimulationSkillBassinRouteImport.update({
  id: '/skill-bassin',
  path: '/skill-bassin',
  getParentRoute: () => SimulationRoute,
} as any);
const RunnersRunnerIdEditRoute = RunnersRunnerIdEditRouteImport.update({
  id: '/$runnerId/edit',
  path: '/$runnerId/edit',
  getParentRoute: () => RunnersRoute,
} as any);

export interface FileRoutesByFullPath {
  '/runners': typeof RunnersRouteWithChildren;
  '/stamina-calculator': typeof StaminaCalculatorRoute;
  '/skill-bassin': typeof SimulationSkillBassinRoute;
  '/uma-bassin': typeof SimulationUmaBassinRoute;
  '/runners/new': typeof RunnersNewRoute;
  '/': typeof SimulationIndexRoute;
  '/runners/': typeof RunnersIndexRoute;
  '/runners/$runnerId/edit': typeof RunnersRunnerIdEditRoute;
}
export interface FileRoutesByTo {
  '/stamina-calculator': typeof StaminaCalculatorRoute;
  '/skill-bassin': typeof SimulationSkillBassinRoute;
  '/uma-bassin': typeof SimulationUmaBassinRoute;
  '/runners/new': typeof RunnersNewRoute;
  '/': typeof SimulationIndexRoute;
  '/runners': typeof RunnersIndexRoute;
  '/runners/$runnerId/edit': typeof RunnersRunnerIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_simulation': typeof SimulationRouteWithChildren;
  '/runners': typeof RunnersRouteWithChildren;
  '/stamina-calculator': typeof StaminaCalculatorRoute;
  '/_simulation/skill-bassin': typeof SimulationSkillBassinRoute;
  '/_simulation/uma-bassin': typeof SimulationUmaBassinRoute;
  '/runners/new': typeof RunnersNewRoute;
  '/_simulation/': typeof SimulationIndexRoute;
  '/runners/': typeof RunnersIndexRoute;
  '/runners/$runnerId/edit': typeof RunnersRunnerIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/runners'
    | '/stamina-calculator'
    | '/skill-bassin'
    | '/uma-bassin'
    | '/runners/new'
    | '/'
    | '/runners/'
    | '/runners/$runnerId/edit';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/stamina-calculator'
    | '/skill-bassin'
    | '/uma-bassin'
    | '/runners/new'
    | '/'
    | '/runners'
    | '/runners/$runnerId/edit';
  id:
    | '__root__'
    | '/_simulation'
    | '/runners'
    | '/stamina-calculator'
    | '/_simulation/skill-bassin'
    | '/_simulation/uma-bassin'
    | '/runners/new'
    | '/_simulation/'
    | '/runners/'
    | '/runners/$runnerId/edit';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  SimulationRoute: typeof SimulationRouteWithChildren;
  RunnersRoute: typeof RunnersRouteWithChildren;
  StaminaCalculatorRoute: typeof StaminaCalculatorRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stamina-calculator': {
      id: '/stamina-calculator';
      path: '/stamina-calculator';
      fullPath: '/stamina-calculator';
      preLoaderRoute: typeof StaminaCalculatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/runners': {
      id: '/runners';
      path: '/runners';
      fullPath: '/runners';
      preLoaderRoute: typeof RunnersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_simulation': {
      id: '/_simulation';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof SimulationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/runners/': {
      id: '/runners/';
      path: '/';
      fullPath: '/runners/';
      preLoaderRoute: typeof RunnersIndexRouteImport;
      parentRoute: typeof RunnersRoute;
    };
    '/_simulation/': {
      id: '/_simulation/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof SimulationIndexRouteImport;
      parentRoute: typeof SimulationRoute;
    };
    '/runners/new': {
      id: '/runners/new';
      path: '/new';
      fullPath: '/runners/new';
      preLoaderRoute: typeof RunnersNewRouteImport;
      parentRoute: typeof RunnersRoute;
    };
    '/_simulation/uma-bassin': {
      id: '/_simulation/uma-bassin';
      path: '/uma-bassin';
      fullPath: '/uma-bassin';
      preLoaderRoute: typeof SimulationUmaBassinRouteImport;
      parentRoute: typeof SimulationRoute;
    };
    '/_simulation/skill-bassin': {
      id: '/_simulation/skill-bassin';
      path: '/skill-bassin';
      fullPath: '/skill-bassin';
      preLoaderRoute: typeof SimulationSkillBassinRouteImport;
      parentRoute: typeof SimulationRoute;
    };
    '/runners/$runnerId/edit': {
      id: '/runners/$runnerId/edit';
      path: '/$runnerId/edit';
      fullPath: '/runners/$runnerId/edit';
      preLoaderRoute: typeof RunnersRunnerIdEditRouteImport;
      parentRoute: typeof RunnersRoute;
    };
  }
}

interface SimulationRouteChildren {
  SimulationSkillBassinRoute: typeof SimulationSkillBassinRoute;
  SimulationUmaBassinRoute: typeof SimulationUmaBassinRoute;
  SimulationIndexRoute: typeof SimulationIndexRoute;
}

const SimulationRouteChildren: SimulationRouteChildren = {
  SimulationSkillBassinRoute: SimulationSkillBassinRoute,
  SimulationUmaBassinRoute: SimulationUmaBassinRoute,
  SimulationIndexRoute: SimulationIndexRoute,
};

const SimulationRouteWithChildren = SimulationRoute._addFileChildren(SimulationRouteChildren);

interface RunnersRouteChildren {
  RunnersNewRoute: typeof RunnersNewRoute;
  RunnersIndexRoute: typeof RunnersIndexRoute;
  RunnersRunnerIdEditRoute: typeof RunnersRunnerIdEditRoute;
}

const RunnersRouteChildren: RunnersRouteChildren = {
  RunnersNewRoute: RunnersNewRoute,
  RunnersIndexRoute: RunnersIndexRoute,
  RunnersRunnerIdEditRoute: RunnersRunnerIdEditRoute,
};

const RunnersRouteWithChildren = RunnersRoute._addFileChildren(RunnersRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  SimulationRoute: SimulationRouteWithChildren,
  RunnersRoute: RunnersRouteWithChildren,
  StaminaCalculatorRoute: StaminaCalculatorRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
